# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
[[constraint]]
  name = "github.com/kataras/iris"
  version = "10.2.1"

[[constraint]]
  name = "github.com/go-pg/pg"
  version = "6.9.6"

[[constraint]]
  name = "github.com/go-pg/migrations"
  version = "6.1.0"

[prune]
  go-tests = true
  unused-packages = true

[metadata.heroku]
  root-package = "github.com/maaaashin324/onsen-tracker"
  go-version = "go1.10"
  install = [".", "./db/..."]
  ensure = "true"
  